default:
  base_dir: "E:\\Github_destop\\Flowers-Classification"

loader:
  traindata_dir: "dataset\\train"
  img_size: 180
  batch_size: 32
  validation_split: 0.2
  

augmentation:
  flip_horizontal: true
  rotation_range: 0.1
  zoom_range: 0.1
  translation_range: 0.1
  brightness_range: 0.2
  crop_percentage: 0.9

data_pretrains:
  data_pretrains: "data_pretrains"

train:
  log_dir: "E:\\Github_destop\\Flowers-Classification\\logs"
  input_shape: (128, 128, 3)
  num_classes: 5
  epochs : 15
  dropout_rate: 0.2
  learning_rate: 0.001
  batch_size: 32
  moder_dir: "E:\\Github_destop\\Flowers-Classification\\model"